site_name: ReportHub Docs
nav:
    - Home: index.md
    - Modules: module.md
    - Services: services.md
    - About: about.md
theme:
  name: material
  palette:
    primary: blue
  

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
